const listText={
ru:{add:'Выбрать',added:'В списке',list:'Ваш список',show:'Показать официанту',chosen:'Выбрано',edit:'Изменить список',close:'Закрыть',remove:'Удалить',total:'Примерная сумма',partial:'Сумма позиций с известной ценой',unknown:'Есть блюда без цены — итог уточните у официанта.',notice:'Официант примет ваш заказ по этому списку.',empty:'Ваш список пока пуст.',clear:'Очистить',variant:'Выберите вариант',unnamed:'Вариант',variantNote:'Размеры или состав вариантов не указаны. Уточните различия у официанта.',portion:'порц.',piece:'шт.',increase:'Увеличить количество',decrease:'Уменьшить количество',choose:'Добавить в список',saved:'Добавлено в список',storage:'Браузер не позволяет сохранить список. Не закрывайте эту страницу.',volume:'л'},
en:{add:'Add',added:'In your list',list:'My list',show:'Show to waiter',chosen:'Selected',edit:'Edit list',close:'Close',remove:'Remove',total:'Estimated total',partial:'Subtotal for priced dishes',unknown:'Some dishes have no price. Ask your waiter for the final total.',notice:'Show this list to your waiter. Your waiter will take the order.',empty:'Your list is empty.',clear:'Clear list',variant:'Choose an option',unnamed:'Option',variantNote:'Option sizes or ingredients are not specified. Ask your waiter about the differences.',portion:'portions',piece:'pcs',increase:'Increase quantity',decrease:'Decrease quantity',choose:'Add to list',saved:'Added to your list',storage:'Your browser cannot save this list. Keep this page open.',volume:'L'},
ka:{add:'დამატება',added:'სიაშია',list:'ჩემი სია',show:'აჩვენეთ მიმტანს',chosen:'არჩეულია',edit:'სიის შეცვლა',close:'დახურვა',remove:'წაშლა',total:'სავარაუდო ჯამი',partial:'ცნობილი ფასების ჯამი',unknown:'ზოგი კერძის ფასი უცნობია. საბოლოო თანხა მიმტანთან დააზუსტეთ.',notice:'აჩვენეთ სია მიმტანს. შეკვეთას მიმტანი მიიღებს.',empty:'თქვენი სია ცარიელია.',clear:'სიის გასუფთავება',variant:'აირჩიეთ ვარიანტი',unnamed:'ვარიანტი',variantNote:'ვარიანტების ზომა ან შემადგენლობა მითითებული არ არის. განსხვავება მიმტანთან დააზუსტეთ.',portion:'პორცია',piece:'ცალი',increase:'რაოდენობის გაზრდა',decrease:'რაოდენობის შემცირება',choose:'სიაში დამატება',saved:'სიაში დაემატა',storage:'ბრაუზერი სიას ვერ ინახავს. არ დახუროთ ეს გვერდი.',volume:'ლ'}
};
const listGuide={
ru:{title:'Составьте список для официанта',copy:'Нажмите «Выбрать» рядом с нужными блюдами. Затем нажмите «Показать официанту» внизу — весь список будет на одном экране.',waiterTitle:'Покажите этот экран официанту',back:'К меню',cleared:'Список очищен',undo:'Вернуть список',options:'Варианты'},
en:{title:'Make a list for your waiter',copy:'Tap “Select” next to the dishes you want. Then tap “Show to waiter” at the bottom to see your whole list on one screen.',waiterTitle:'Show this screen to your waiter',back:'Back to menu',cleared:'List cleared',undo:'Restore list',options:'Options'},
ka:{title:'შეადგინეთ სია მიმტანისთვის',copy:'სასურველ კერძებთან დააჭირეთ „არჩევა“-ს. შემდეგ ქვემოთ დააჭირეთ „აჩვენეთ მიმტანს“-ს — მთელი სია ერთ ეკრანზე გამოჩნდება.',waiterTitle:'აჩვენეთ ეს ეკრანი მიმტანს',back:'მენიუში დაბრუნება',cleared:'სია გასუფთავებულია',undo:'სიის აღდგენა',options:'ვარიანტები'}
};
listText.en.add='Select';listText.ka.add='არჩევა';
let clearedSelections=null,undoTimer;
const listCatalog=new Map();
for(const c of categories) c[4].forEach((d,i)=>listCatalog.set(c[0]+':'+i,{dish:d,category:c[0]}));
function canonicalListId(id){return id==='adjara:4'?'bakery:3':id;}
function dishOptions(id){id=canonicalListId(id);const entry=listCatalog.get(id);if(!entry)return [];const prices=entry.dish[3]===null?[null]:entry.dish[3].split('/').map(p=>Math.round(Number(p.trim().replace(',','.'))*100));
 let labels=null;
 if(id==='fish:3'){prices.push(prices[0]);labels=[['В баже','In walnut sauce','ბაჟეში'],['В соусе из кориандра и уксуса','In coriander & vinegar sauce','ქინძმარში']];}
 if(id==='fish:0')labels=[['Жареная','Fried','შემწვარი'],['С грецкими орехами','With walnuts','ნიგვზით']];
 if(id==='wine:2')labels=[['Виноградная','Grape','ყურძნის'],['Дынная','Melon','ნესვის'],['Персиковая','Peach','ატმის'],['Медовая','Honey','თაფლის']];
 if(id==='wine:1')labels=['0,5','1'].map(v=>[v+' л',v.replace(',','.')+' L',v+' ლ']);
 if(id==='wine:11')labels=['0,2','0,35','0,5'].map(v=>[v+' л',v.replace(',','.')+' L',v+' ლ']);
 if(entry.category==='spirits'&&(prices.length>1||entry.dish[3]===null)){const volumes=entry.dish[0].split('·')[1].trim().replace(/\s*л$/,'').split('/').map(s=>s.trim());labels=volumes.map(v=>[v+' л',v.replace(',','.')+' L',v+' ლ']);if(entry.dish[3]===null){prices.splice(0,prices.length,...volumes.map(()=>null));}}
 return prices.map((price,index)=>({price,label:labels?.[index]||null,index}));}
let selections=[];let listStorageFailed=false;let listMode='edit';let pendingDish=null;
try{const raw=JSON.parse(localStorage.getItem('ardagani-my-list-v1')||'[]');if(Array.isArray(raw)){for(const row of raw){if(!row||typeof row.id!=='string')continue;const id=canonicalListId(row.id),options=dishOptions(id);if(!Number.isInteger(row.option)||!options[row.option]||!Number.isInteger(row.quantity)||row.quantity<1)continue;const found=selections.find(x=>x.id===id&&x.option===row.option);if(found)found.quantity=Math.min(999,found.quantity+row.quantity);else selections.push({id,option:row.option,quantity:Math.min(999,row.quantity)});}}}catch{}
const listEl=id=>document.getElementById(id);
function money(cents){return new Intl.NumberFormat(lang==='ka'?'ka-GE':lang==='en'?'en-US':'ru-RU',{maximumFractionDigits:2}).format(cents/100)+' ₾';}
function optionName(option){return option.label?option.label[languageIndex()]:listText[lang].unnamed+' '+(option.index+1);}
function selectionControl(id){
 const key=canonicalListId(id),t=listText[lang],d=listCatalog.get(key).dish,name=escapeHTML(d[languageIndex()]);
 const rows=selections.filter(x=>x.id===key),n=rows.reduce((sum,x)=>sum+x.quantity,0);
 if(!n)return `<button class="add-dish" data-add="${id}" type="button" aria-label="${t.choose}: ${name}"><span aria-hidden="true">＋</span> ${t.add}</button>`;
 if(dishOptions(key).length>1)return `<button class="add-dish in-list" data-add="${id}" type="button" aria-label="${t.choose}: ${name}"><span aria-hidden="true">＋</span> ${t.add}<span class="dish-selected">${t.chosen}: ${n}</span></button>`;
 return `<div class="dish-quantity"><button type="button" data-dish-decrease="${id}" aria-label="${t.decrease}: ${name}">−</button><span aria-label="${t.chosen}: ${n}">${n}</span><button type="button" data-add="${id}" aria-label="${t.increase}: ${name}" ${n>=999?'disabled':''}>＋</button></div>`;
}
function addButton(id){return `<div class="selection-control" data-selection="${id}">${selectionControl(id)}</div>`;}
function dismissUndo(){clearTimeout(undoTimer);clearedSelections=null;listEl('list-undo-notice').hidden=true;}
function clearSelections(){if(!selections.length)return;clearTimeout(undoTimer);clearedSelections=selections.map(row=>({...row}));selections=[];saveSelections();if(listEl('list-dialog').open)listEl('list-dialog').close();listEl('list-undo-notice').hidden=false;listEl('list-undo').focus();undoTimer=setTimeout(dismissUndo,15000);}
function openList(mode){listMode=mode;renderList();listEl('list-dialog').showModal();}

function saveSelections(){try{localStorage.setItem('ardagani-my-list-v1',JSON.stringify(selections));listStorageFailed=false}catch{listStorageFailed=true}renderList();}
function addSelection(id,option){id=canonicalListId(id);if(!dishOptions(id)[option])return;dismissUndo();let row=selections.find(x=>x.id===id&&x.option===option);if(row)row.quantity=Math.min(999,row.quantity+1);else selections.push({id,option,quantity:1});saveSelections();listEl('list-status').textContent=listText[lang].saved;}
function requestAdd(id){id=canonicalListId(id);const options=dishOptions(id);if(options.length===1){addSelection(id,0);return}pendingDish=id;const t=listText[lang];const d=listCatalog.get(id).dish;listEl('variant-title').textContent=t.variant;listEl('variant-name').textContent=d[languageIndex()];listEl('variant-close').innerHTML=icon('close');listEl('variant-close').setAttribute('aria-label',t.close);listEl('variant-options').innerHTML=options.map(o=>`<button type="button" data-option="${o.index}"><span>${escapeHTML(optionName(o))}</span><strong>${o.price===null?ui[lang].unknown:money(o.price)+equivalentHTML(o.price/100)}</strong></button>`).join('');listEl('variant-note').textContent=options.some(o=>!o.label)?t.variantNote:'';listEl('variant-dialog').showModal();}
function renderList(){const t=listText[lang],g=listGuide[lang],ix=languageIndex();listEl('order-help-title').textContent=g.title;listEl('order-help-copy').textContent=g.copy;listEl('list-cleared').textContent=g.cleared;listEl('list-undo').textContent=g.undo;let quantity=0,total=0,unknown=false;for(const row of selections){quantity+=row.quantity;const p=dishOptions(row.id)[row.option].price;if(p===null)unknown=true;else total+=p*row.quantity;}
 listEl('list-bar').hidden=!selections.length;document.body.classList.toggle('has-list',!!selections.length);listEl('list-count').textContent=t.list+' · '+quantity;listEl('list-bar-total').textContent=(unknown?t.partial+': ':'')+money(total);listEl('list-bar-clear').textContent=t.clear;listEl('list-show').textContent=t.show;listEl('list-title').textContent=listMode==='waiter'?g.waiterTitle:t.list;listEl('list-notice').textContent=t.notice;listEl('list-close').textContent=g.back;listEl('list-close').setAttribute('aria-label',g.back);listEl('list-mode').textContent=listMode==='edit'?t.show:t.edit;listEl('list-mode').hidden=!selections.length;listEl('list-clear').textContent=t.clear;listEl('list-clear').hidden=!selections.length;listEl('list-dialog').classList.toggle('waiter-mode',listMode==='waiter');listEl('list-storage').textContent=listStorageFailed?t.storage:'';
 listEl('list-items').innerHTML=selections.length?selections.map((row,index)=>{const entry=listCatalog.get(row.id),d=entry.dish,o=dishOptions(row.id)[row.option],unit=entry.category==='khinkali'?t.piece:t.portion;return `<article class="list-item"><div class="list-item-title"><h3>${escapeHTML(d[ix])}</h3><strong>× ${row.quantity}</strong></div>${lang!=='ka'?`<p class="georgian-name" lang="ka">${escapeHTML(d[2])}</p>`:''}${dishOptions(row.id).length>1?`<p>${escapeHTML(optionName(o))}${lang!=='ka'&&o.label?' · '+escapeHTML(o.label[2]):''}</p>`:''}<p>${row.quantity} ${unit} · ${o.price===null?ui[lang].unknown:money(o.price*row.quantity)}</p><div class="list-controls"><button type="button" data-change="${index}" data-delta="-1" aria-label="${t.decrease}: ${escapeHTML(d[ix])}" ${row.quantity===1?'disabled':''}>−</button><span>${row.quantity}</span><button type="button" data-change="${index}" data-delta="1" aria-label="${t.increase}: ${escapeHTML(d[ix])}" ${row.quantity>=999?'disabled':''}>＋</button><button class="remove-item" type="button" data-remove="${index}">${t.remove}</button></div></article>`}).join(''):`<p class="list-empty">${t.empty}</p>`;
 listEl('list-total').textContent=(unknown?t.partial:t.total)+': '+money(total);listEl('list-total').hidden=!selections.length;listEl('list-unknown').textContent=unknown?t.unknown:'';const equivalent=equivalentText(total/100);listEl('list-total-equivalent').textContent=equivalent;listEl('list-total-equivalent').hidden=!selections.length||!equivalent;
 document.querySelectorAll('[data-selection]').forEach(b=>{b.innerHTML=selectionControl(b.dataset.selection);});
}
document.addEventListener('click',e=>{const add=e.target.closest('[data-add]'),decrease=e.target.closest('[data-dish-decrease]');if(add){const id=add.dataset.add;requestAdd(id);if(!listEl('variant-dialog').open)document.querySelector(`[data-selection="${id}"] [data-add]`)?.focus({preventScroll:true});}if(decrease){const id=canonicalListId(decrease.dataset.dishDecrease),row=selections.find(x=>x.id===id);if(row){row.quantity--;selections=selections.filter(x=>x.quantity>0);saveSelections();document.querySelector(`[data-selection="${decrease.dataset.dishDecrease}"] button`)?.focus({preventScroll:true});}}});
listEl('variant-options').addEventListener('click',e=>{const b=e.target.closest('[data-option]');if(!b||!pendingDish)return;addSelection(pendingDish,Number(b.dataset.option));listEl('variant-dialog').close();const id=pendingDish;pendingDish=null;document.querySelector(`[data-selection="${id}"] button`)?.focus({preventScroll:true});});
listEl('variant-close').onclick=()=>listEl('variant-dialog').close();
listEl('list-show').onclick=()=>openList('waiter');
listEl('list-open').onclick=()=>openList('edit');
listEl('list-bar-clear').onclick=clearSelections;
listEl('list-undo').onclick=()=>{if(!clearedSelections)return;selections=clearedSelections;dismissUndo();saveSelections();listEl('list-open').focus();};
listEl('list-close').onclick=()=>listEl('list-dialog').close();
listEl('list-mode').onclick=()=>{listMode=listMode==='edit'?'waiter':'edit';renderList()};
listEl('list-clear').onclick=clearSelections;
listEl('list-items').addEventListener('click',e=>{const change=e.target.closest('[data-change]'),remove=e.target.closest('[data-remove]');if(change){const row=selections[Number(change.dataset.change)];if(row)row.quantity=Math.max(1,Math.min(999,row.quantity+Number(change.dataset.delta)));saveSelections()}if(remove){selections.splice(Number(remove.dataset.remove),1);saveSelections()}});
